theme:
  name: material
  language: zh
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - content.action.edit
  plugins:
    - search:
        lang: zh
    - offline
    - git-revision-date-localized:
        enabled: true
        enable_creation_date: true
    - git-committers:
        repository: zliao555/zliao555.github.io
        branch: master
        enabled: true
  icon:
    repo: fontawesome/brands/github
site_name: 电力电子飞跃手册
repo_url: https://github.com/zliao555/zliao555.github.io
repo_name: zliao555/zliao555.github.io
edit_uri: edit/master/docs/